server:
  port: 8080
  servlet:
    context-path: /mall

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/mall?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    hikari:
      username: root
      password: root
#      mysql版本 >= 6.x com.mysql.cj.jdbc.Driver
#      mysql版本 <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: Auto
      table-underline: true # 默认数据库字段为下划线格式
      logic-delete-field: del_flag  # 逻辑删除字段
      logic-delete-value: 1 # 删除
      logic-not-delete-value: 0 # 正常
  configuration:
    call-setters-on-nulls: true
  type-enums-package: com.young.common.enums # 枚举类型

logging:
  config: classpath:logback-spring.xml
  level:
    com.young.generator.mapper: debug

# ===== 自定义swagger配置 ===== #
springfox:
  documentation:
    swagger-ui:
      enabled: true
