server:
  port: 8080
  servlet:
    context-path: /mall

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  redis:
    host: localhost
    port: 6379
#    password: 123456
    lettuce:
      pool:
        max-active: 300
  datasource:
    url:  jdbc:mysql://localhost:3306/mall?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    hikari:
      username: root
      password: root
#      mysql版本 >= 6.x com.mysql.cj.jdbc.Driver
#      mysql版本 <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: assign_uuid
      table-underline: true # 默认数据库字段为下划线格式
      logic-delete-field: del_flag  # 逻辑删除字段
      logic-delete-value: 1 # 删除
      logic-not-delete-value: 0 # 正常
  configuration:
    call-setters-on-nulls: true
  type-enums-package: com.young.common.enums # 枚举类型

logging:
  config: classpath:logback-spring.xml
  level:
    com.young.generator.mapper: debug

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: com.young.mall
  local:
    # 默认2小时本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 3600000
      expireAfterAccessInMillis: 1800000
    # 長時本地緩存，主要用于要求时效一般
    longTime:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 300000
      expireAfterAccessInMillis: 180000
    # 短時本地緩存，主要用于要求时效较高的配置
    shortTime:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 60000
      expireAfterAccessInMillis: 40000
  remote:
    # 默认2小时的远程缓存
    default:
      type: redis
      expireAfterWriteInMillis: 43200000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    # 长时远程緩存，主要用于要求时效要求一般的集中式缓存
    longTime:
      type: redis
      expireAfterWriteInMillis: 7200000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    # 短時远程緩存，主要用于要求时效较高的集中式缓存
    shortTime:
      type: redis
      expireAfterWriteInMillis: 300000
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
